
// This file has been generated by the GUI designer. Do not modify.
namespace ClerkOffice.UI
{
	public partial class ClerkLoginWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ClerkOffice.UI.ClerkLoginWindow
			this.Name = "ClerkOffice.UI.ClerkLoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ClerkLoginWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
