
// This file has been generated by the GUI designer. Do not modify.

public partial class ClerkLoginWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Entry entUsername;
	
	private global::Gtk.Entry entPassword;
	
	private global::Gtk.Button btnLogin;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget ClerkLoginWindow
		this.Name = "ClerkLoginWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("ClerkLoginWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child ClerkLoginWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entUsername = new global::Gtk.Entry ();
		this.entUsername.CanFocus = true;
		this.entUsername.Name = "entUsername";
		this.entUsername.IsEditable = true;
		this.entUsername.InvisibleChar = '●';
		this.vbox1.Add (this.entUsername);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entUsername]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entPassword = new global::Gtk.Entry ();
		this.entPassword.CanFocus = true;
		this.entPassword.Name = "entPassword";
		this.entPassword.IsEditable = true;
		this.entPassword.InvisibleChar = '●';
		this.vbox1.Add (this.entPassword);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entPassword]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnLogin = new global::Gtk.Button ();
		this.btnLogin.CanFocus = true;
		this.btnLogin.Name = "btnLogin";
		this.btnLogin.UseUnderline = true;
		this.btnLogin.Label = global::Mono.Unix.Catalog.GetString ("Login");
		this.vbox1.Add (this.btnLogin);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnLogin]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 93;
		this.Show ();
		this.btnLogin.Clicked += new global::System.EventHandler (this.OnBtnLoginClicked);
	}
}
