
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Button btnWaitingRoom;
	
	private global::Gtk.Button btnClerkOffice;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.btnWaitingRoom = new global::Gtk.Button ();
		this.btnWaitingRoom.CanFocus = true;
		this.btnWaitingRoom.Name = "btnWaitingRoom";
		this.btnWaitingRoom.UseUnderline = true;
		this.btnWaitingRoom.Label = global::Mono.Unix.Catalog.GetString ("Waiting Room");
		this.vbox2.Add (this.btnWaitingRoom);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnWaitingRoom]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.btnClerkOffice = new global::Gtk.Button ();
		this.btnClerkOffice.CanFocus = true;
		this.btnClerkOffice.Name = "btnClerkOffice";
		this.btnClerkOffice.UseUnderline = true;
		this.btnClerkOffice.Label = global::Mono.Unix.Catalog.GetString ("Clerk Office");
		this.vbox2.Add (this.btnClerkOffice);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnClerkOffice]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 60;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnWaitingRoom.Clicked += new global::System.EventHandler (this.OnBtnWaitingRoomClicked);
		this.btnClerkOffice.Clicked += new global::System.EventHandler (this.OnBtnClerkOfficeClicked);
	}
}
