
// This file has been generated by the GUI designer. Do not modify.

public partial class WaitingRoomWindow
{
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Button btnTicket;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget WaitingRoomWindow
		this.Name = "WaitingRoomWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("WaitingRoomWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child WaitingRoomWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnTicket = new global::Gtk.Button ();
		this.btnTicket.CanFocus = true;
		this.btnTicket.Name = "btnTicket";
		this.btnTicket.UseUnderline = true;
		this.btnTicket.Label = global::Mono.Unix.Catalog.GetString ("Ticket");
		this.vbox4.Add (this.btnTicket);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnTicket]));
		w1.Position = 1;
		w1.Expand = false;
		w1.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.btnTicket.Clicked += new global::System.EventHandler (this.OnBtnTicketClicked);
	}
}
